name: Jest CI

on:
  push:
    branches:
      - master         # Despliegue en producción
      - julio          # Ramas de desarrollo
      - irving         # Ramas de desarrollo
      - jesus          # Ramas de desarrollo
      - feature/*
  pull_request:
    branches:
      - master         
      - julio          
      - irving         
      - jesus          
  workflow_dispatch:   # Activación manual opcional

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2      

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'          

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install --save-dev @testing-library/jest-dom --legacy-peer-deps  # Instala jest-dom para pruebas

      - name: Run Jest tests
        run: npx jest --ci --coverage --env=jsdom
