name: PWA CI/CD Workflow

on:
  push:
    branches:
      - master         # Despliegue en producción
      - julio          # Ramas de desarrollo
      - irving         # Ramas de desarrollo
      - jesus          # Ramas de desarrollo
      - feature/*      # Ramas de características
  pull_request:
    branches:
      - master         # Validar cambios en solicitudes de extracción hacia master
      - julio          # Validar cambios en solicitudes de extracción hacia julio
      - irving         # Validar cambios en solicitudes de extracción hacia irving
      - jesus          # Validar cambios en solicitudes de extracción hacia jesus
  workflow_dispatch:   # Activación manual opcional

jobs:
  build:
    runs-on: ubuntu-latest   # Sistema operativo

    steps:
      - name: Checkout code
        uses: actions/checkout@v2   # Clonar el repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'         # Especificar la versión de Node.js

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm               # Caché de dependencias de npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install             # Instalar dependencias

      - name: Run tests
        run: npm test                # Ejecutar pruebas

      - name: Build project
        run: npm run build           # Compilar el proyecto

  cypress:
    runs-on: ubuntu-latest
    needs: build                     # Espera a que se complete el trabajo de build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2     # Clonar el repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'          # Especificar la versión de Node.js

      - name: Install Cypress
        run: npm install cypress       # Instalar Cypress

      - name: Run Cypress tests
        run: npx cypress run           # Ejecutar las pruebas de Cypress

  deploy:
    runs-on: ubuntu-latest
    needs: build                     # Espera a que se complete el trabajo de build
    if: github.ref == 'refs/heads/master'   # Desplegar solo desde la rama master

    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying to production..." # Comando para desplegar, puede ser un script o comando específico
