name: Vitest CI

on:
  push:
    branches:
      - main            # Despliegue en producción (cambiar 'master' a 'main' si es tu rama principal)
      - julio           # Rama de desarrollo
      - irving          # Rama de desarrollo
      - jesus           # Rama de desarrollo
      - feature/*       # Cualquier rama feature
  pull_request:
    branches:
      - main            # Rama de producción para las solicitudes de pull
      - julio           # Rama de desarrollo para las solicitudes de pull
      - irving          # Rama de desarrollo para las solicitudes de pull
      - jesus           # Rama de desarrollo para las solicitudes de pull
  workflow_dispatch:     # Activación manual opcional

jobs:
  vitest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Clonar el repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Configurar la versión de Node.js

      - name: Install dependencies
        run: npm install --legacy-peer-deps  # Instalar dependencias del proyecto

      - name: Install Vite (si es necesario)
        run: npm install --save-dev vite  # Asegurarse de que Vite esté instalado

      - name: Install Vitest
        run: npm install --save-dev vitest  # Instalar Vitest como dependencia de desarrollo

      - name: Run Vitest
        run: npm run test:unit  # Ejecutar las pruebas de Vitest
