name: Vitest CI

on:
  push:
    branches:
      - main            # Despliegue en producci贸n
      - julio           # Ramas de desarrollo
      - irving          # Ramas de desarrollo
      - jesus           # Ramas de desarrollo
      - feature/*       # Cualquier rama feature
  pull_request:
    branches:
      - main            # Rama de producci贸n para las solicitudes de pull
      - julio           # Rama de desarrollo para las solicitudes de pull
      - irving          # Rama de desarrollo para las solicitudes de pull
      - jesus           # Rama de desarrollo para las solicitudes de pull
  workflow_dispatch:     # Activaci贸n manual opcional

jobs:
  vitest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Clonar el repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Configurar la versi贸n de Node.js

      - name: Install dependencies
        run: npm install --legacy-peer-deps  # Usar --legacy-peer-deps para resolver dependencias


      - name: Install Vitest
        run: npm install --save-dev vitest  # Instalar Vitest como dependencia de desarrollo

      - name: Run Vitest
        run: npm run test:unit  # Ejecutar las pruebas de Vitest
